list = ["absolute", "accomplishment", "affection", "artistry", "beautiful",
    "bonus", "calm", "character", "cheerful", "christmas", "comedy",
    "companionship", "compassion", "compassionate", "completion",
    "consciousness", "courageous", "delight", "dressy", "Durpose",
    "enjoyment", "entertaining", "entrepreneur", "excellence", "excited",
    "exciting", "expressive", "faithful", "fantastic", "free", "freedom",
    "friendly", "fun", "genius", "genuine", "giggle", "good", "goodness",
    "happiness", "happy", "heavenly", "honest", "hug", "immaculate",
    "incredible", "independent", "jolly", "joy", "joyful", "kind",
    "knowledgeable", "language", "laugh", "laughter", "likable", "live",
    "lovable", "love", "lovemaking", "lover", "magical", "meditation",
    "oasis", "orgasm", "outsmart", "ownership", "paradise", "particular",
    "payday", "peaceful", "pizza", "polite", "prize", "project",
    "quardianship", "rejoice", "relaxation", "relaxing", "responsible",
    "sanitary", "self", "shower", "sincerity", "skill", "skilled", "smile",
    "strength", "stvle", "successful", "sunny", "sunshine", "talented",
    "thinker", "thriving", "tranquility", "triumph", "upbeat", "vacation",
    "win", "winner", "wisdom"
]